### ISSUE TITLE
Problem with :confirmable and :invitable

### ISSUE THREAD

**Issue by ghost** [RailsApps/rails-prelaunch-signup#32]
I have followed the tutorial steps exactly, as far as I am aware, and I have two issues:

1) Including ":invitable" in the user model causes all sorts of problems. I had to include the gem 'devise_invitable'

2) I am getting this error:

Scenario: User signs up with valid data                         # features/visitors/request_invitation.feature:18
    When I request an invitation with valid user data             # features/step_definitions/visitor_steps.rb:42
      undefined local variable or method `confirmed_at' for #<User:0x007fe7c36bddb8> (NameError)
      ./app/models/user.rb:29:in`active_for_authentication?'
      ./features/step_definitions/visitor_steps.rb:9:in `invitation_request'
      ./features/step_definitions/visitor_steps.rb:43:in`/^I request an invitation with valid user data$/'
      features/visitors/request_invitation.feature:19:in `When I request an invitation with valid user data'

I followed some advice in gett8ing :confirmable to work in Devise v2.0 by creating the migration:

class AddConfirmableToDeviseV1 < ActiveRecord::Migration
  def change
    change_table(:users) do |t|
      t.string   :confirmation_token
      t.datetime :confirmed_at
      t.datetime :confirmation_sent_at
    end
    add_index  :users, :confirmation_token, :unique => true
  end
end

and running rake db:migrate. However, this has not resolved the issue. Any help on both these issues would be greatly appreciated.

**Comment by ghost** [comment]
devise 2.2.2 is installed.

**Comment by ghost** [comment]
After updating the user model with the :confirmable fields, I needed to run db:test:prepare.
